### ISSUE TITLE
Kaartsymbolen voertuigen. 

### ISSUE THREAD

**Issue by rienkmossel** [imroi/kaartsymbolen#1]
Hoi, 

1. De kaartsymbolen van voertuigen kunnen als verwarrend ervaren worden. Dit doordat de tekst en het plaatje de zelfde kleur zijn. Met name bij de WTS lijkt het net alsof er WTSI staat, is het een idee om de tekstkleur aan te passen naar een andere kleur dan het van voertuig zelf?
2. Is het daarnaast mogelijk om nog twee voertuigen toe te voegen ten behoeve opstelplaats. 
GWV (grootschalige watervoorziening) en een WO (waterongevallenvoertuig.) 

Zie voorbeeld hoe een dergelijk plaatje eruit zou kunnen zien, in dit voorbeeld zwarte letters. 
![gwv](https://user-images.githubusercontent.com/58828613/225688173-860c261e-3316-422f-8c7e-28a759891481.svg)

Gr Rienk Mossel 
Veiligheidsregio Groningen

**Comment by baasgeo** [comment]
Hoi, punt 1 lijkt me een prima verbetering. Punt 2 kan ik niet zo goed inschatten.

@MarkTwisk-VRFGV en @RemcoVolger wat vinden jullie van dit voorstel?

**Comment by MarkTwisk-VRFGV** [comment]
Ik zie verder niets

Met vriendelijke groet

[signature_2994630786]

Mark Twisk
Vakinhoudelijk Coördinator Planvorming
Informatie Manager CoPI/ROT

Brandweer Flevoland & Gooi en Vechtstreek
Postbus 10334, 1301 AH Almere
Gordiaandreef 101, 8233 AB Lelystad
T 0900-0165
M 06-82506954
Teams ***@***.***



Van: Bart Baas ***@***.***>
Beantwoorden - Aan: imroi/kaartsymbolen ***@***.***>
Datum: dinsdag 21 maart 2023 om 14:04
Aan: imroi/kaartsymbolen ***@***.***>
CC: Mark Twisk ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [imroi/kaartsymbolen] Kaartsymbolen voertuigen. (Issue #1)

Waarschuwing: deze e-mail komt van een extern adres. Klik niet op links of open geen bijlagen, tenzij je zeker weet dat de inhoud veilig is. Neem bij twijfel contact op met de helpdesk ICT via ***@***.***


Hoi, punt 1 lijkt me een prima verbetering. Punt 2 kan ik niet zo goed inschatten.

@MarkTwisk-VRFGV<https://github.com/MarkTwisk-VRFGV> en @RemcoVolger<https://github.com/RemcoVolger> wat vinden jullie van dit voorstel?

**Comment by MarkTwisk-VRFGV** [comment]
Voor nu een goede aanpassing tot dat de landelijke symbolen set beschikbaar is.
Wat betreft punt 2, als het goed is zal er 1 generaal symbool opstelplaats voertuig komen waar voor de specifieke er een label aan vast zal zitten. Tussentijds toevoegen lijkt mij oke.

**Comment by RemcoVolger** [comment]
Goedemiddag heren,

Ben het eens met Mark.

Ik ben wel benieuwd naar de nieuwe landelijke symbolen?

Vriendelijke groet,

Remco Volger
Informatiegestuurde Incidentbestrijding (IGIB)

M 06 25 39 56 42

***@***.***
Brandweer Amsterdam-Amstelland
Kazerne Nico | IJ-tunnel 4 | 1011 TA | Amsterdam
www.brandweeraa.nl<http://www.brandweeraa.nl>





Van: MarkTwisk-VRFGV ***@***.***>
Verzonden: dinsdag 21 maart 2023 14:13
Aan: imroi/kaartsymbolen ***@***.***>
CC: Volger, Remco ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [imroi/kaartsymbolen] Kaartsymbolen voertuigen. (Issue #1)


Voor nu een goede aanpassing tot dat de landelijke symbolen set beschikbaar is.
Wat betreft punt 2, als het goed is zal er 1 generaal symbool opstelplaats voertuig komen waar voor de specifieke er een label aan vast zal zitten. Tussentijds toevoegen lijkt mij oke.

**Comment by baasgeo** [comment]
De symbolen van de huidige voertuigen zijn aangepast, zie pull request #3 

Voor een preview van de wijziging, zie https://github.com/imroi/kaartsymbolen/pull/3/files

Indien akkoord @rienkmossel en @MarkTwisk-VRFGV dan zal ik de pull request verwerken
