### ISSUE TITLE
Sleutelkluis Symbool

### ISSUE THREAD

**Issue by paulvanderheijden90** [imroi/kaartsymbolen#11]
Wij als VRMWB gebruikte altijd een "Rode sleutelkluis" Symbool voor plaatsen waar een sleutekluis geplaatst is waar wij met iets vanuit een voertuig toegang to hebben. Viro sleutel Octro sleutel Code of tag.
Nu dit niet meer gewenst is zijn deze rode sleutelkluizen uit gefaseerd op onze kaarten. 

We hebben nog wel Sleutelkluizen die open gestuurd kunnen worden door een handeling of elektronisch. Dit worden er alleen maar meer.
Wij hebben deze sleutelkluisjes blauw gemaakt. Zo zie je in 1 oog opslag welke sleutelkluisjes al zijn aangepast.

![image](https://github.com/imroi/kaartsymbolen/assets/40613554/88fc5d31-62b1-4d14-bc56-39c172298611)
Graag willen we deze ook in Cogo gebruiken.

**Comment by baasgeo** [comment]
Zie het voorstel voor het nieuwe symbool https://github.com/imroi/kaartsymbolen/pull/12/files

**Comment by baasgeo** [comment]
Zie het voorstel voor het bijgewerkte symbool https://github.com/imroi/kaartsymbolen/pull/14/files
