### ISSUE TITLE
Zwarte tekst UGS symbool in GeoServer

### ISSUE THREAD

**Issue by 16-vrhm** [imroi/kaartsymbolen#13]
Hi,

Wanneer we het UGS-symbool (208) gebruiken in de verbeelding/styling, dan rendert GeoServer de "UGS" tekst zwart. Dit zou gewoon wit moeten blijven. Gaat om dit symbool: https://imroi.github.io/kaartsymbolen/iconen/voorziening/208.svg

gr,
Roy

**Comment by baasgeo** [comment]
Dank voor het melden Roy, dit is zojuist gecorrigeerd
