### ISSUE TITLE
Eisen besluit bouwwerken leefomgeving omtrent laadpunten in parkeergarages

### ISSUE THREAD

**Issue by paulvanderheijden90** [imroi/kaartsymbolen#15]
Hallo,

Wij als Afdeling IOA ( Informatie Onderzoek en Analyse ) hebben een verzoek gekregen van de afdeling RB om mee te denken over een aanpassing in het bouw besluit van 2024. 

**Inhoudelijk:** 
1 januari 2024 gaan er een aantal wetswijzigingen binnen de omgevingswet van kracht. Zo gaat het bouwbesluit 2012 (welke wij momenteel hanteren voor onze regelgerichte advisering bij vergunningen en toezicht) over in het besluit bouwwerken leefomgeving.

_Voor wat betreft oplaadpunten voor elektrische voertuigen komen er een aantal eisen bij. Één artikel die ons raakt is o.a. 4.230a. Zie hieronder:

Artikel 4.230a (oplaadpunten elektrische voertuigen)

1. Een overige gebruiksfunctie voor het stallen van motorvoertuigen heeft een voorziening waarmee de oplaadpunten voor elektrische voertuigen tegelijkertijd kunnen worden uitgeschakeld. 

2. Bij de toegang voor motorvoertuigen van een overige gebruiksfunctie voor het stallen van motorvoertuigen is kenbaar hoe de in eerste lid bedoelde voorziening is uitgevoerd en waar de oplaadpunten voor elektrische voortuigen zich bevinden._

**Vraag die ons gesteld wordt:**
Het lijkt mij voor de hand liggend dat we hier regionaal eenzelfde lijn in trekken.

Een voorbeeld kan zijn dat we bij de knop voor gelijktijdige uitschakeling van alle oplaadpunten in de garage een “B” symbool plaatsen, deze voorziening wordt opgenomen in de operationele viewer.
Een ander voorbeeld kan zijn dat we hier geen aandacht aan geven en dat de gebruiker eigenaar moet zorgen dat er voldaan wordt aan artikel 1 en 2. Dus zij maken dit kenbaar met bijvoorbeeld een verduurzaamde plattegrond bij de entree van de parkeergarage met tevens een aanduiding van waar deze centrale afschakeling zich bevindt.
Een ander voorbeeld kan zijn dat we in een operationele viewer in beeld brengen waar parkeergarages aanwezig zijn.

**Concreet:**
Kunnen we binnen het IMROI model een symbool/werkafspraak maken? 
Bijv: Als we dit in Cogo gaan aangeven met een symbool. Kunnen we dit symbool bij de fysieke schakelaar hangen. 
Ook kunnen we de plaats van de schakelaar dan aanduiden middels Cogo in de operationele viewers.

**Comment by baasgeo** [comment]
Als ik het goed begrijp dan gaat het om een nieuw symbool van een voorziening om elektrisch laden uit te kunnen schakelen. @SjoerdJS of @RemcoVolger kunnen jullie hier iets over zeggen?

**Comment by RemcoVolger** [comment]
![laadpaal](https://github.com/imroi/kaartsymbolen/assets/128149872/8d80a498-6dbd-4e62-97ae-08db38975ed6)
Hi Bart, als dat de wens is zullen we zo'n symbool moeten maken. Ik was laatst in een parkeergarage bij een oriëntatie en die had zo'n systeem zelf geïnstalleerd. En die was ook zoekende hoe hij dit kon aangeven voor de brandweer, hij heeft er uiteindelijk voor gekozen om er een rood bordje met een B boven te hangen. Maar denk dat we daarvoor inderdaad een landelijk symbool voor moeten maken. Volgens mij hebben we een werkgroep voor symbolen dus dat zal dan via deze groep moeten???

**Comment by RemcoVolger** [comment]
Er boven staat het symbool wat we nu gebruiken voor opladen elektrische voertuigen.

**Comment by paulvanderheijden90** [comment]
Hallo,
Ja er is zeker behoefte aan aan symbool. We willen die gebruiken om de plaats van de knop aan te geven. 
Ook willen we het symbool gebruiken om bij de knop in de panden zelf te hangen.

**Comment by paulvanderheijden90** [comment]
Hallo @RemcoVolger @baasgeo @SjoerdJS 
Hebben jullie een idee wanneer we een opzet van het Icoon kunnen verwachten ? 
2024 duurt nog even maar we krijgen al wel de vraag van gebouw eigenaren en willen die in 1 keer goed adviseren.

**Comment by RemcoVolger** [comment]
![afsluiter laadpaal](https://github.com/imroi/kaartsymbolen/assets/128149872/d554873e-7553-41c8-859a-c7f6bc783aff)
![afsluiter laadpaal v2](https://github.com/imroi/kaartsymbolen/assets/128149872/a2e890c0-ecef-46d2-80b0-6e36986165bf)
![afsluiter laadpaal v3](https://github.com/imroi/kaartsymbolen/assets/128149872/12160de2-505c-4f90-b7a9-3b2b414a3bbe)

Hoi Paul,
Hierbij drie voorstellen voor een **tijdelijk** symbool, dit omdat er ook een traject loopt voor een landelijke symbolen set via het NIPV. Waarbij nu de offerte goedgekeurd moet gaan worden. Dan zal hij dus in lijn worden met deze set, zodat het eenduidig gaat worden.

**Comment by paulvanderheijden90** [comment]
Hallo @RemcoVolger,
Ziet er goed uit! Ook duidelijk wat mijn betreft.
Wanneer verwacht je dat het nipv het goedkeurt en we het kunnen gebruiken?

**Comment by RemcoVolger** [comment]
Hi Paul, nogmaals wat ik nu heb gemaakt is een tijdelijke oplossing. Omdat er dus een landelijke set komt. Het NIPV is op dit moment offertes aan het goedkeuren en daarna zal er een lijst komen met symbolen die dan een extern bureau gaat ontwerpen. Hierdoor onstaat er een landelijke lijn zodat alle regio’s dezelfde symbolen gaan hanteren. Mijn gevoel zegt dat dit nog wel een half jaar gaat duren. Ik heb morgen een overleg met de werkgroep dat is voor mij ook de eerste keer dat ik daarbij aansluit. Ik zal deze vraag meenemen en jou daarna antwoord geven op wanneer ze denken dat de symbolen klaar zijn. Tot die tijd mag je een van de drie symbolen gebruiken als tijdelijke oplossing. Ik kan het op dit moment niet mooier maken. En ikzelf hoop morgen ook wat wijzer te worden.

**Comment by paulvanderheijden90** [comment]
Hallo heren,
Willen jullie delen met Bart Baas van Cogo
![image](https://github.com/imroi/kaartsymbolen/assets/40613554/535d96ea-8132-44fe-9f22-4f00b86ac969)

**Comment by baasgeo** [comment]
Bovenstaande symbool is toegevoegd onder nummer 754, zie commit [#332803e](https://github.com/imroi/kaartsymbolen/commit/332803ecc87ce115c7ecfd08eefeadc1a38dc1b3) voor instructies
