### ISSUE TITLE
Brandwerende scheidingen

### ISSUE THREAD

**Issue by VRGroningen** [imroi/kaartsymbolen#18]
Ik merk bij nieuwe objecten dat er vaak een 90 minuten brandwerende scheiding is en we hier nog geen keuze in hebben in cogo.
Is er een symbologie brandwerende scheidingen ergens vastgelegd waar dit aan moet voldoen, zodat we de keuze kunnen uitbreiden.
ik moet nu vaak met het label de juiste waarde aangeven ,maar als op de IPAD de lijn word bevraagd, geeft die de waarde aan van de gekozen 60 minuten lijn en ontstaat er verwarring of het nu 90 of 60 minuten is.
In de NEN 2014 _2019 staan enkel 30 en 60 minuten benoemd

**Comment by baasgeo** [comment]
Wanneer andere regio's hier ook behoefte aan hebben dan is dit prima te realiseren, @SjoerdJS of @CoenNengerman weten jullie misschien of andere regio's deze behoefte ook hebben?

**Comment by SjoerdJS** [comment]
In het zojuist vastgestelde IMROI model is de waarde 90 minuten brandscheiding niet opgenomen als waarde, zie ook 
https://geonovum.github.io/IMROI/#detail_class_IMROIDomein_TypeBouwkundigeVoorziening

Als dit een breed gedragen wens is kan de waarde uiteraard worden toegevoegd in het informatiemodel. Voor de korte termijn is het verstandig om de scheiding als 60 minuten te registreren met een evt aanvulling (label oid)
