### ISSUE TITLE
Verbeteren sleutelkluis symbolen

### ISSUE THREAD

**Issue by baasgeo** [imroi/kaartsymbolen#2]
Er is momenteel geen onderscheid tussen sleutel- _buis_ en sleutel- _kluis_. Met een kleine aanpassing - een cirkel en een vierkant - is dit visuaal te maken.

**Comment by baasgeo** [comment]
Gefixed via https://github.com/imroi/kaartsymbolen/commit/36a0246dc931a957922cd8374e5b688d82b4ae83

**Comment by MarkTwisk-VRFGV** [comment]
Ik kan geen status veranderen van deze bug

**Comment by VRGroningen** [comment]
ik zie dat deze wisseling van invloed is geweest op onze symbool weergave.
onze sleutelbuis  symbolen zijn nu de ronde variant geworden, doordat 302 de ronde variant is geworden!.

**Comment by baasgeo** [comment]
Inderdaad omdat er voorheen geen onderscheid was tussen symbool id 302 en 301, kan het zijn dat door deze wijziging de symbolen wijzigen. Het is een kwestie van de tabel bijwerken van 302 naar 301 om dit op te lossen
