### ISSUE TITLE
WTS opstel plaats./ Openwater geschikt voor WTS

### ISSUE THREAD

**Issue by paulvanderheijden90** [imroi/kaartsymbolen#20]
Hallo,
Ik ben opzoek naar een Icoon voor een opstelplaats WTS systeem. 
Is deze er ? zo niet zou iemand die willen maken ?

mvg
Paul

**Comment by baasgeo** [comment]
Is symbool 104 uit de voertuigen waar je naar op zoek bent?

https://github.com/imroi/kaartsymbolen/blob/main/iconen/voertuig/104.svg

**Comment by paulvanderheijden90** [comment]
Hallo Toch wil ik deze nog eens openen. Ik heb de vraag verkeert gesteld. Ik was opzoek naar een symbool dat aangeeft dat water geschikt is als openwater voor een WTS.  Een grafisch vormgever heeft daar voor ons dit van gemaakt. willen jullie die opnemen in het IMroi model ?
![Openwater-WTS](https://github.com/user-attachments/assets/73358c51-a4c9-4e8a-b5be-f10e0f52866a)
