### ISSUE TITLE
Nieuw Icoontje Evenementen - Verkeersregelaar

### ISSUE THREAD

**Issue by Maarten-Visser-VGGM** [imroi/kaartsymbolen#21]
Hoi, 

Voor ROI - Evenementen - Verkeersregelaar ben ik op zoek naar een mooi passend icoontje i.v.m. een komend wielerevent waar er veel komen te staan.

Alvast bedankt.
Groet Maarten Visser
Veiligheidsregio Gelderland Midden

**Comment by baasgeo** [comment]
@RemcoVolger zou jij dit symbool kunnen maken voor Evenementen?

**Comment by RemcoVolger** [comment]
![verkeersregelaar](https://github.com/imroi/kaartsymbolen/assets/128149872/0d9b1f38-f859-4ee8-9df5-9368a22c44f6)
![verkeersregelaar](https://github.com/imroi/kaartsymbolen/assets/128149872/4c62f670-c04a-45d2-a9ce-b0112b6228b8)

**Comment by RemcoVolger** [comment]
zoiets?

**Comment by Maarten-Visser-VGGM** [comment]
Ziet er goed uit! Dank voor je snelle werk. 
Komt deze ook openbaar beschikbaar om over te nemen in de GeoServer?

Groet Maarten Visser

**Comment by baasgeo** [comment]
Het nieuwe symbool kan worden toegevoegd aan de opzoektabel via onderstaande SQL statement.

```
INSERT INTO roi.symbool (id, naam, omschrijving)
VALUES (161, 'Verkeersregelaar', NULL);
```

Voeg vervolgens nummer 161 toe aan het symbool_id veld van de voorzieningen tabel in Cogo Collect.

Dank @RemcoVolger voor je snelle actie

**Comment by baasgeo** [comment]
Zie commit https://github.com/imroi/kaartsymbolen/commit/87763d3b03d1e16fab197943a03ea1e71c4b3e38
