### ISSUE TITLE
Icoon vastgesteld in MWB voor: "Informatie EOS"

### ISSUE THREAD

**Issue by paulvanderheijden90** [imroi/kaartsymbolen#22]
Beste,

In Midden en West Brabant willen we middels een kaartlaag de EOS systemen in de wijk gaan tonen. Het gaat om een laag in ons eigen beheer. Verreikt met landelijke info, 

Hiervoor hebben we een Icoon laten maken die we graag landelijk willen delen.

Bijdeze.

![EOS Systeem Picto](https://github.com/user-attachments/assets/890b866b-c28b-42a4-97ec-9b4e0d8f33b8)

**Comment by baasgeo** [comment]
Wat mij betreft prima om op te nemen. @RemcoVolger kan dit bestand 1-op-1 worden overgenomen of zijn er nog bewerkingen nodig?

**Comment by RemcoVolger** [comment]
Hebben ze dit symbool ook als SVG?

**Comment by baasgeo** [comment]
Toegevoegd via 5f7eed29dcf09102fbc69b1de07ad7de906cb0a3

**Comment by baasgeo** [comment]
Het nieuwe symbool kan worden toegevoegd aan de opzoektabel via onderstaande SQL statement.

```
INSERT INTO roi.symbool (id, naam, omschrijving)
VALUES (755, 'Afsluiter elektrische voertuigen (EOS)', NULL);
```

Voeg vervolgens nummer 755 toe aan het symbool_id veld van de voorzieningen tabel in Cogo Collect.

Dank @RemcoVolger voor het maken van het symbool
