### ISSUE TITLE
Toevoeging van symbolen t.b.v. Objecten (onderscheid) en Evenementen (opstelplaats-voertuigtypes)

### ISSUE THREAD

**Issue by Maarten-Visser-VGGM** [imroi/kaartsymbolen#4]
Hoi,

Het zou heel mooi zijn als er enkele symbolen toegevoegd kunnen worden.

Objecten zijn nu enkel te onderscheiden in statussen en niet in type Object.
(https://github.com/imroi/kaartsymbolen/tree/main/iconen/object)

Graag zouden we dan ook verschillende Objecten typen krijgen voor:
•	Evenementen
•	Gebouwen
•	Natuurbrand
•	Spoor
•	Waterongevallen

Ook is er onder de Evenementen (Topic) nu geen onderscheid te maken voor Opstelplaatsen van andere disciplines dan Brandweer, zoals Politie Ambulance GHOR (en Multi).
Voertuig voorstel rode TS in diverse passende kleuren
(https://github.com/imroi/kaartsymbolen/blob/main/iconen/voertuig/101.svg)

•	Brandweer (is er nu)
•	Politie 
•	Ambulance 
•	GHOR 
•	(en Multi. Overig?).

Alvast bedankt.

**Comment by baasgeo** [comment]
Opgesplitst in twee aparte issues om de twee vragen separaat te kunnen afronden
