### ISSUE TITLE
Symbool Meterkast is verkeerd

### ISSUE THREAD

**Issue by paulvanderheijden90** [imroi/kaartsymbolen#5]
Ik zie dat het symbool van de Elektra meterkast niet goed is. Hier staan ook de symbolen van Water en Gas bij. 

![image](https://user-images.githubusercontent.com/40613554/234197416-1e9b278e-3e31-4cf6-80b8-cc1adcea95bd.png)

![image](https://user-images.githubusercontent.com/40613554/234197510-f87b5f1e-fd4b-47ab-920b-b7754838a7c1.png)

Wanneer deze word aangepast naar alleen een Elektra meterkast mis ik daarna de meterkast met Gas Water en Elektra. Deze zou aangemaakt moeten worden.

**Comment by baasgeo** [comment]
Zo te zien is er inderdaad geen symbool voor een meterkast met alleen elektra. Is het een idee om een nieuw symbool te maken er id 717 hiervoor te gebruiken @RemcoVolger ? Dit nummer is nog vrij.

Link: https://imroi.github.io/kaartsymbolen/iconen/voorziening/

**Comment by RemcoVolger** [comment]
Goedemorgen het klopt dat deze er niet is omdat we daarvoor een los symbool hebben afsluiter electra. 
link: https://imroi.github.io/kaartsymbolen/iconen/voorziening/702.svg
Voor de meterkasten hebben we alleen gekozen om symbolen daarin samen te voegen zodat we niet alle afsluiters los hoeven te plaatsen. Je heb dus de keuze of losse afsluiters of in een meterkast waardoor je maar een symbool hoeft toe te voegen.

Maar mocht dit niet de wens zijn dan hoor ik het graag.

**Comment by RemcoVolger** [comment]
Vervolg op mijn antwoord van net is dat het symbool dus niet klopt wat eraan hangt deze moet verandert worden naar symbool #702.

**Comment by baasgeo** [comment]
Volgens mij is deze keurig, en kan zo gemerged worden, zie preview:

https://github.com/imroi/kaartsymbolen/pull/6/files

**Comment by baasgeo** [comment]
Ter info, het nieuwe symbool kan worden toegevoegd aan de opzoektabel via onderstaande SQL statement.

```
INSERT INTO roi.symbool (id, naam, omschrijving)
VALUES (717, 'Meterkast elektra', NULL);
```

Voeg vervolgens nummer 717 toe aan het symbool_id veld van de voorzieningen tabel in Cogo Collect.
