### ISSUE TITLE
Toevoegen object typen

### ISSUE THREAD

**Issue by baasgeo** [imroi/kaartsymbolen#8]
Zoals beschreven in #4 is dit een verbeterpunt voor het toevoegen van extra object typen voor:
• Evenementen
• Gebouwen
• Natuurbrand
• Spoor
• Waterongevallen

**Comment by baasgeo** [comment]
Zie preview: https://github.com/imroi/kaartsymbolen/pull/10/files

**Comment by MarkTwisk-VRFGV** [comment]
Netjes
